from .baseMethod import *
from .boardInfo import *
from .eltest import *
from .oftest import *
from .kick import *
from .ledtest import *
from .list import *
from .load import *
from .pause import *
from .play import *
from .quit import *
from .reboot import *
from .send import *
from .sendLight import *
from .shutDown import *
from .statuslight import *
from .stop import *
from .sync import *
from .uploadJsonFile import *
