#!/usr/bin/env sh

USERNAME="pi"
WORKSPACE="/home/pi/LightDance-RPi"

git config --global user.email "ntuee@ntu.edu.tw"
git config --global user.name "lightdance"

sudo timedatectl set-ntp no

# copy authorized_keys
mkdir -p /home/$USERNAME/.ssh
cp $WORKSPACE/authorized_keys /home/$USERNAME/.ssh/

# client.py requirements
cd $WORKSPACE/ws_client
pip3 install -r requirements.txt

# build and set daemon
cd $WORKSPACE/scripts
./build
./set-service

# HOSTNAME=$1
# SERVER_IP=$2

# ./set-hostname.sh $HOSTNAME
# ./set-server-ip.sh $SERVER_IP
