#!/usr/bin/env sh

# USERNAME=$1
# WORKSPACE="${2/#\~/$HOME}"
#
# cp system/player.service.template system/player.service
# sed -i "s!<USERNAME>!${USERNAME}!g" system/player.service
# sed -i "s!<WORKSPACE>!${WORKSPACE}!g" system/player.service
#
# cp system/client.service.template system/client.service
# sed -i "s!<USERNAME>!${USERNAME}!g" system/client.service
# sed -i "s!<WORKSPACE>!${WORKSPACE}!g" system/client.service

WORKSPACE="/home/pi/LightDance-RPi"

cd $WORKSPACE/system
sudo cp player.service /etc/systemd/system/
sudo cp client.service /etc/systemd/system/
sudo cp startup.service /etc/systemd/system/

sudo systemctl daemon-reload
sudo systemctl enable player.service
sudo systemctl enable client.service
sudo systemctl enable startup.service
sudo systemctl start player.service
sudo systemctl start client.service
sudo systemctl start startup.service
