#!/usr/bin/env sh

USERNAME="pi"
WORKSPACE="/home/pi/LightDance-RPi"

cd $WORKSPACE
git stash && git pull
rm -rf controller/hardware
git submodule update --init
cd $WORKSPACE/controller/hardware
git checkout main
git pull
